export { default as DashboardLayout } from './DashboardLayout'
export { default as Landing } from './LandingPage'
export { default as HomeLayout } from './HomeLayout'
export { default as Register } from './Register'
export { default as Login} from './Login'
export { default as Error } from './Error'
export { default as Stats } from './Stats'
export { default as AllOrphanage } from './AllOrphanage'
export { default as AddOrphanage } from './AddOrphanage'
export { default as EditOrphanage } from './EditOrphanage'
export { default as Profile } from './Profile'
export { default as Admin } from './Admin'
export { default as Explore } from './Explore'